### ISSUE TITLE
Inspect sfdc-apex-rollbar repo in depth

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-sf-apex#6]
Seems like one of our users has already built his own SDK: https://github.com/ebth/sfdc-apex-rollbar

From what I've seen so far it's as far as this SDK. However, a more in-depth inspection would be useful to see how this developer approached building the SDK.

**Comment by waltjones** [comment]
We seem to already be ahead of this, though it's cool to see the interest in Rollbar in Apex 3 years ago.
